### ISSUE TITLE
Nullable argument

### ISSUE THREAD

**Issue by niolap** [hasura/go-graphql-client#87]
I would like to pass a null argument as my GraphQL endpoint support null arguments. But it does not work.

My code:

```go
type MyMutation struct {
  MyMutation struct {
	  Integer int
  } `graphql:"myMutation(input: {objectName: $objectName, variables: $variables})"`
}

parameters := map[string]interface{}{
  "objectName": "my-object",
  "variables": nil, // Here I indicate a null "value"
}
err := s.UserInput.graphqlClient.Mutate(context.Background(), &MyMutation, parameters)
```

But it panics at run time:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x6a0177]

goroutine 1 [running]:
github.com/hasura/go-graphql-client.writeArgumentType({0x7c1040, 0xc00017e2d0}, {0x0, 0x0?}, {0x0, 0x0}, 0x1)
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/query.go:139 +0x57
github.com/hasura/go-graphql-client.queryArguments(0xc00017e1b0)
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/query.go:126 +0x350
github.com/hasura/go-graphql-client.ConstructMutation({0x6d5da0?, 0xc0001780b0?}, 0xc00017e1b0, {0x0, 0x0, 0x0})
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/query.go:80 +0x219
github.com/hasura/go-graphql-client.(*Client).buildAndRequest(0x10?, {0x7c3710, 0xc00001e5d8}, 0x34?, {0x6d5da0?, 0xc0001780b0?}, 0x40c427?, {0x0, 0x0, 0x0})
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:112 +0x8f
github.com/hasura/go-graphql-client.(*Client).do(0x11?, {0x7c3710?, 0xc00001e5d8?}, 0x58?, {0x6d5da0, 0xc0001780b0}, 0xc00016f960?, {0x0, 0x0, 0x0})
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:246 +0x65
github.com/hasura/go-graphql-client.(*Client).Mutate(...)
        /home/nico/go/pkg/mod/github.com/hasura/go-graphql-client@v0.9.0/graphql.go:66
main.(*Server).update(0xc000178000)
```

**Comment by hgiasac** [comment]
The issue could be in the binding type, not variable. You can define either:

```go
// type MyMutation struct {
var MyMutation struct {
  MyMutation struct {
	  Integer int
  } `graphql:"myMutation(input: {objectName: $objectName, variables: $variables})"`
}
``` 

or

```go
type MyMutation struct {
  MyMutation struct {
	  Integer int
  } `graphql:"myMutation(input: {objectName: $objectName, variables: $variables})"`
}

q := MyMutation{}

err := s.UserInput.graphqlClient.Mutate(context.Background(), &q, parameters)
```
